default['ihs']['user_id'] = 'rusa'
default['ihs']['group'] = 'sgsup'
default['ihs']['root'] = '/apps/ihs-bin'
default['ihs']['conf_root'] = '/apps/ihs-apps'
#default['ihs']['sec_root'] = '/opt/ihsSec'
