Vagrant.configure("2") do |config|
    config.vm.define :dmgr do |dmgr_config|
      dmgr_config.vm.box = "redhat-6.5-devops"
      dmgr_config.proxy.http = "http://webproxy.wlb2.nam.nsroot.net:8080"
      dmgr_config.proxy.https = "http://webproxy.wlb2.nam.nsroot.net:8080"
      dmgr_config.vm.network "private_network", ip: "192.168.1.10"
      dmgr_config.vm.network :forwarded_port, guest: 10000, host: 9998
      dmgr_config.vm.network :forwarded_port, guest: 10001, host: 9999
      dmgr_config.vm.hostname = "dmgr.websphere.vagrant.internal"
      dmgr_config.vm.provision "hosts", sync_hosts:"true"
      dmgr_config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = "C:\\Users\\ms66518\\chef-repo\\cookbooks\\"
        chef.add_recipe "wsi::default"
        chef.add_recipe "wsi::install_iim_was"
        chef.add_recipe "wsi::create_dmgr_profile"
        #chef.add_recipe "wsi::create_cluster"
        #chef.add_recipe "wsi::add_first_cluster_member"
        #chef.add_recipe "wsi::add_cluster_members"
        #chef.add_recipe "wsi::create_oracle_jdbc"
        #chef.add_recipe "wsi::create_jms_mq_qcf"
        #chef.add_recipe "wsi::create_jms_mq_queues"
        #chef.add_recipe "wsi::update_generic_jvm"
        #chef.add_recipe "wsi::add_custom_jvm_props"
        #chef.add_recipe "wsi::update_thread_pool"
      end
    end
    config.vm.define :node1 do |node1_config|
      node1_config.vm.box = "redhat-6.5-devops"
      node1_config.proxy.http = "http://webproxy.wlb2.nam.nsroot.net:8080"
      node1_config.proxy.https = "http://webproxy.wlb2.nam.nsroot.net:8080"
      node1_config.vm.network "private_network", ip: "192.168.1.11"
      node1_config.vm.hostname = "node1.websphere.vagrant.internal"
      node1_config.vm.provision "hosts", sync_hosts:"true"
      node1_config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = "C:\\Users\\ms66518\\chef-repo\\cookbooks\\"
        chef.add_recipe "wsi::default"
        chef.add_recipe "wsi::install_iim_was"
        chef.add_recipe "wsi::create_node_profile"
        chef.add_recipe "wsi::add_node"
      end
    end
end
